In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def gen_sphere_harm_basis(nodes, degree):
    x, y , z = nodes[:,0], nodes[:,1], nodes[:,2]
    num_cols = (degree + 1)**2
    P = np.zeros((n, num_cols))
    j = 0
    for k in range(degree+1):
        if k == 0:
            P[:,j] = 1+0*x
            j += 1
        if k == 1:
            P[:,j] = y
            j += 1
            P[:,j] = z
            j += 1
            P[:,j] = x
            j += 1
        if k == 2:
            P[:,j] = x*y
            j += 1
            P[:,j] = y*z
            j += 1
            P[:,j] = 3*z**2 - 1
            j += 1
            P[:,j] = x*z
            j += 1
            P[:,j] = x**2 - y**2
            j += 1
        if k == 3:
            P[:,j] = y*(-3*x**2 + y**2)
            j += 1
            P[:,j] = x*y*z
            j += 1
            P[:,j] = y*(1 - 5*z**2)
            j += 1
            P[:,j] = z*(-3 + 5*z**2)
            j += 1
            P[:,j] = x*(1 - 5*z**2)
            j += 1
            P[:,j] = z*(x**2 - y**2)
            j += 1
            P[:,j] = x*(x**2 - 3*y**2)
            j += 1
        if k == 4:
            P[:,j] = x*y*(x**2 - y**2)
            j += 1
            P[:,j] = y*z*(y**2 - 3*x**2)
            j += 1
            P[:,j] = x*y*(-1 + 7*z**2)
            j += 1
            P[:,j] = y*z*(3 - 7*z**2)
            j += 1
            P[:,j] = 35*z**4 - 30*z**2 + 3
            j += 1
            P[:,j] = x*z*(3 - 7*z**2)
            j += 1
            P[:,j] = (x**2 - y**2)*(-1 + 7*z**2)
            j += 1
            P[:,j] = x*z*(x**2 - 3*y**2)
            j += 1
            P[:,j] = x**4 - 6*x**2*y**2 + y**4
            j += 1
        if k == 5:
            P[:,j] = y*(5*x**4-10*x**2*y**2+ y**4)
            j += 1
            P[:,j] = x*y*(x**2-1*y**2)*z
            j += 1
            P[:,j] = y*(-3*x**2+y**2)*(-1+9*z**2)
            j += 1
            P[:,j] = x*y*z*(-1+3*z**2)
            j += 1
            P[:,j] = y*(1-14*z**2+21*z**4)
            j += 1
            P[:,j] = z*(15-70*z**2+63*z**4)
            j += 1
            P[:,j] = x*(1-14*z**2+21*z**4)
            j += 1
            P[:,j] = (x**2-y**2)*z*(-1+3*z**2)
            j += 1
            P[:,j] = x*(x**2-3*y**2)*(-1+9*z**2)
            j += 1
            P[:,j] = (x**4-6*x**2*y**2+y**4)*z
            j += 1
            P[:,j] = x*(x**4-10*x**2*y**2+5*y**4)
            j += 1
        if k == 6:
            P[:,j] = x*y*(3*x**4-10*x**2*y**2+3*y**4)            
            j += 1
            P[:,j] = y*(5*x**4-10*x**2*y**2+y**4)*z
            j += 1
            P[:,j] = x*y*(x**2-y**2)*(-1+11*z**2)
            j += 1
            P[:,j] = y*(-3*x**2+y**2)*z*(-3+11*z**2)
            j += 1
            P[:,j] = x*y*(1-18*z**2+33*z**4)
            j += 1
            P[:,j] = y*z*(5-30*z**2+33*z**4)
            j += 1
            P[:,j] = (-5+105*z**2-315*z**4+231*z**6)
            j += 1
            P[:,j] = x*z*(5-30*z**2+33*z**4)
            j += 1
            P[:,j] = (x**2-y**2)*(1-18*z**2+33*z**4)
            j += 1
            P[:,j] = x*(x**2-3*y**2)*z*(-3+11*z**2)
            j += 1
            P[:,j] = (x**4-6*x**2*y**2+y**4)*(-1+11*z**2)
            j += 1
            P[:,j] = x*(x**4-10*x**2*y**2+5*y**4)*z
            j += 1
            P[:,j] = (x**6-15*x**4*y**2+15*x**2*y**4-y**6)
            j += 1
        if k == 7:
            P[:,j] = y*((-7)*x**6+35*x**4*y**2+(-21)*x**2*y**4+y**6)
            j += 1
            P[:,j] = x*y*(3*x**4+(-10)*x**2*y**2+3*y**4)*z
            j += 1
            P[:,j] = y*(5*x**4+(-10)*x**2*y**2+y**4)*((-1)+13*z**2)
            j += 1
            P[:,j] = x*y*(x**2+(-1)*y**2)*z*((-3)+13*z**2)
            j += 1
            P[:,j] = y*((-3)*x**2+y**2)*(3+(-66)*z**2+143*z**4)
            j += 1
            P[:,j] = x*y*z*(15+(-110)*z**2+143*z**4)
            j += 1
            P[:,j] = y*(5+(-135)*z**2+495*z**4+(-429)*z**6)
            j += 1
            P[:,j] = z*((-35)+315*z**2+(-693)*z**4+429*z**6)
            j += 1
            P[:,j] = x*(5+(-135)*z**2+495*z**4+(-429)*z**6)
            j += 1
            P[:,j] = (x**2+(-1)*y**2)*z*(15+(-110)*z**2+143*z**4)
            j += 1
            P[:,j] = x*(x**2+(-3)*y**2)*(3+(-66)*z**2+143*z**4)
            j += 1
            P[:,j] = (x**4+(-6)*x**2*y**2+y**4)*z*((-3)+13*z**2)
            j += 1
            P[:,j] = x*(x**4+(-10)*x**2*y**2+5*y**4)*((-1)+13*z**2)
            j += 1
            P[:,j] = (x**6+(-15)*x**4*y**2+15*x**2*y**4+(-1)*y**6)*z
            j += 1
            P[:,j] = x*(x**6+(-21)*x**4*y**2+35*x**2*y**4+(-7)*y**6)
            j += 1
            
    rhs_x = np.zeros((n, num_cols))
    
    rhs_y = np.zeros((n, num_cols))
    
    rhs_z = np.zeros((n, num_cols))
    
    return P

In [3]:
n = 5

indices = np.arange(0, n, dtype=float) + 0.5
phi = np.arccos(1 - 2*indices/n)
theta = np.pi * (1 + 5**0.5) * indices
xs, ys, zs = np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)
nodes = np.array([(x,y,z) for x,y,z in zip(xs,ys,zs)])

In [4]:
nodes

array([[ 2.17424934e-01, -5.59219454e-01,  8.00000000e-01],
       [-8.21915033e-01,  4.05531353e-01,  4.00000000e-01],
       [ 9.60144597e-01,  2.79503761e-01,  6.12323400e-17],
       [-4.75835108e-01, -7.83314082e-01, -4.00000000e-01],
       [-1.16695329e-01,  5.88542437e-01, -8.00000000e-01]])

In [5]:
P = gen_sphere_harm_basis(nodes, 7)
P2 = gen_sphere_harm_basis2(nodes, 7)
P-P2

NameError: name 'gen_sphere_harm_basis2' is not defined

In [44]:
print(P[:,4] - nodes[:,0]*nodes[:,1])

[0. 0. 0. 0. 0.]


In [46]:
P.shape

(5, 64)

In [36]:
xs

array([ 0.21742493, -0.82191503,  0.9601446 , -0.47583511, -0.11669533])

In [37]:
nodes

array([[ 2.17424934e-01, -5.59219454e-01,  8.00000000e-01],
       [-8.21915033e-01,  4.05531353e-01,  4.00000000e-01],
       [ 9.60144597e-01,  2.79503761e-01,  6.12323400e-17],
       [-4.75835108e-01, -7.83314082e-01, -4.00000000e-01],
       [-1.16695329e-01,  5.88542437e-01, -8.00000000e-01]])

In [6]:
sphere_harm = []
sphere_harm.append( lambda x, y , z :1+0*x)
sphere_harm.append( lambda x, y , z :y)
sphere_harm.append( lambda x, y , z :z)
sphere_harm.append( lambda x, y , z :x)
sphere_harm.append( lambda x, y , z :x*y)
sphere_harm.append( lambda x, y , z :y*z)
sphere_harm.append( lambda x, y , z :3*z**2 - 1)
sphere_harm.append( lambda x, y , z :x*z)
sphere_harm.append( lambda x, y , z :x**2 - y**2)
sphere_harm.append( lambda x, y , z :y*(-3*x**2 + y**2))
sphere_harm.append( lambda x, y , z :x*y*z)
sphere_harm.append( lambda x, y , z :y*(1 - 5*z**2))
sphere_harm.append( lambda x, y , z :z*(-3 + 5*z**2))
sphere_harm.append( lambda x, y , z :x*(1 - 5*z**2))
sphere_harm.append( lambda x, y , z :z*(x**2 - y**2))
sphere_harm.append( lambda x, y , z :x*(x**2 - 3*y**2))
sphere_harm.append( lambda x, y , z :x*y*(x**2 - y**2))
sphere_harm.append( lambda x, y , z :y*z*(y**2 - 3*x**2))
sphere_harm.append( lambda x, y , z :x*y*(-1 + 7*z**2))
sphere_harm.append( lambda x, y , z :y*z*(3 - 7*z**2))
sphere_harm.append( lambda x, y , z :35*z**4 - 30*z**2 + 3)
sphere_harm.append( lambda x, y , z :x*z*(3 - 7*z**2))
sphere_harm.append( lambda x, y , z :(x**2 - y**2)*(-1 + 7*z**2))
sphere_harm.append( lambda x, y , z :x*z*(x**2 - 3*y**2))
sphere_harm.append( lambda x, y , z :x**4 - 6*x**2*y**2 + y**4)
sphere_harm.append( lambda x, y , z :y*(5*x**4-10*x**2*y**2+ y**4))
sphere_harm.append( lambda x, y , z :x*y*(x**2-1*y**2)*z)
sphere_harm.append( lambda x, y , z :y*(-3*x**2+y**2)*(-1+9*z**2))
sphere_harm.append( lambda x, y , z :x*y*z*(-1+3*z**2))
sphere_harm.append( lambda x, y , z :y*(1-14*z**2+21*z**4))
sphere_harm.append( lambda x, y , z :z*(15-70*z**2+63*z**4))
sphere_harm.append( lambda x, y , z :x*(1-14*z**2+21*z**4))
sphere_harm.append( lambda x, y , z :(x**2-y**2)*z*(-1+3*z**2))
sphere_harm.append( lambda x, y , z :x*(x**2-3*y**2)*(-1+9*z**2))
sphere_harm.append( lambda x, y , z :(x**4-6*x**2*y**2+y**4)*z)
sphere_harm.append( lambda x, y , z :x*(x**4-10*x**2*y**2+5*y**4))
sphere_harm.append( lambda x, y , z :x*y*(3*x**4-10*x**2*y**2+3*y**4))
sphere_harm.append( lambda x, y , z :y*(5*x**4-10*x**2*y**2+y**4)*z)
sphere_harm.append( lambda x, y , z :x*y*(x**2-y**2)*(-1+11*z**2))
sphere_harm.append( lambda x, y , z :y*(-3*x**2+y**2)*z*(-3+11*z**2))
sphere_harm.append( lambda x, y , z :x*y*(1-18*z**2+33*z**4))
sphere_harm.append( lambda x, y , z :y*z*(5-30*z**2+33*z**4))
sphere_harm.append( lambda x, y , z :(-5+105*z**2-315*z**4+231*z**6))
sphere_harm.append( lambda x, y , z :x*z*(5-30*z**2+33*z**4))
sphere_harm.append( lambda x, y , z :(x**2-y**2)*(1-18*z**2+33*z**4))
sphere_harm.append( lambda x, y , z :x*(x**2-3*y**2)*z*(-3+11*z**2))
sphere_harm.append( lambda x, y , z :(x**4-6*x**2*y**2+y**4)*(-1+11*z**2))
sphere_harm.append( lambda x, y , z :x*(x**4-10*x**2*y**2+5*y**4)*z)
sphere_harm.append( lambda x, y , z :(x**6-15*x**4*y**2+15*x**2*y**4-y**6))
sphere_harm.append( lambda x, y , z :y*((-7)*x**6+35*x**4*y**2+(-21)*x**2*y**4+y**6))
sphere_harm.append( lambda x, y , z :x*y*(3*x**4+(-10)*x**2*y**2+3*y**4)*z)
sphere_harm.append( lambda x, y , z :y*(5*x**4+(-10)*x**2*y**2+y**4)*((-1)+13*z**2))
sphere_harm.append( lambda x, y , z :x*y*(x**2+(-1)*y**2)*z*((-3)+13*z**2))
sphere_harm.append( lambda x, y , z :y*((-3)*x**2+y**2)*(3+(-66)*z**2+143*z**4))
sphere_harm.append( lambda x, y , z :x*y*z*(15+(-110)*z**2+143*z**4))
sphere_harm.append( lambda x, y , z :y*(5+(-135)*z**2+495*z**4+(-429)*z**6))
sphere_harm.append( lambda x, y , z :z*((-35)+315*z**2+(-693)*z**4+429*z**6))
sphere_harm.append( lambda x, y , z :x*(5+(-135)*z**2+495*z**4+(-429)*z**6))
sphere_harm.append( lambda x, y , z :(x**2+(-1)*y**2)*z*(15+(-110)*z**2+143*z**4))
sphere_harm.append( lambda x, y , z :x*(x**2+(-3)*y**2)*(3+(-66)*z**2+143*z**4))
sphere_harm.append( lambda x, y , z :(x**4+(-6)*x**2*y**2+y**4)*z*((-3)+13*z**2))
sphere_harm.append( lambda x, y , z :x*(x**4+(-10)*x**2*y**2+5*y**4)*((-1)+13*z**2))
sphere_harm.append( lambda x, y , z :(x**6+(-15)*x**4*y**2+15*x**2*y**4+(-1)*y**6)*z)
sphere_harm.append( lambda x, y , z :x*(x**6+(-21)*x**4*y**2+35*x**2*y**4+(-7)*y**6) )

sphere_harm_grad_x = []
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :1)
sphere_harm_grad_x.append( lambda x, y , z :y)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :z)
sphere_harm_grad_x.append( lambda x, y , z :2*x)
sphere_harm_grad_x.append( lambda x, y , z :-6*x*y)
sphere_harm_grad_x.append( lambda x, y , z :y*z)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :-5*z**2 + 1)
sphere_harm_grad_x.append( lambda x, y , z :2*x*z)
sphere_harm_grad_x.append( lambda x, y , z :3*x**2 - 3*y**2)
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*y + y*(x**2 - y**2))
sphere_harm_grad_x.append( lambda x, y , z :-6*x*y*z)
sphere_harm_grad_x.append( lambda x, y , z :y*(7*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :z*(-7*z**2 + 3))
sphere_harm_grad_x.append( lambda x, y , z :2*x*(7*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*z + z*(x**2 - 3*y**2))
sphere_harm_grad_x.append( lambda x, y , z :4*x**3 - 12*x*y**2)
sphere_harm_grad_x.append( lambda x, y , z :y*(20*x**3 - 20*x*y**2))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*y*z + y*z*(x**2 - y**2))
sphere_harm_grad_x.append( lambda x, y , z :-6*x*y*(9*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :y*z*(3*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :21*z**4 - 14*z**2 + 1)
sphere_harm_grad_x.append( lambda x, y , z :2*x*z*(3*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*(9*z**2 - 1) + (x**2 - 3*y**2)*(9*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :z*(4*x**3 - 12*x*y**2))
sphere_harm_grad_x.append( lambda x, y , z :x**4 - 10*x**2*y**2 + x*(4*x**3 - 20*x*y**2) + 5*y**4)
sphere_harm_grad_x.append( lambda x, y , z :x*y*(12*x**3 - 20*x*y**2) + y*(3*x**4 - 10*x**2*y**2 + 3*y**4))
sphere_harm_grad_x.append( lambda x, y , z :y*z*(20*x**3 - 20*x*y**2))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*y*(11*z**2 - 1) + y*(x**2 - y**2)*(11*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :-6*x*y*z*(11*z**2 - 3))
sphere_harm_grad_x.append( lambda x, y , z :y*(33*z**4 - 18*z**2 + 1))
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :z*(33*z**4 - 30*z**2 + 5))
sphere_harm_grad_x.append( lambda x, y , z :2*x*(33*z**4 - 18*z**2 + 1))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*z*(11*z**2 - 3) + z*(x**2 - 3*y**2)*(11*z**2 - 3))
sphere_harm_grad_x.append( lambda x, y , z :(4*x**3 - 12*x*y**2)*(11*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :x*z*(4*x**3 - 20*x*y**2) + z*(x**4 - 10*x**2*y**2 + 5*y**4))
sphere_harm_grad_x.append( lambda x, y , z :6*x**5 - 60*x**3*y**2 + 30*x*y**4)
sphere_harm_grad_x.append( lambda x, y , z :y*(-42*x**5 + 140*x**3*y**2 - 42*x*y**4))
sphere_harm_grad_x.append( lambda x, y , z :x*y*z*(12*x**3 - 20*x*y**2) + y*z*(3*x**4 - 10*x**2*y**2 + 3*y**4))
sphere_harm_grad_x.append( lambda x, y , z :y*(20*x**3 - 20*x*y**2)*(13*z**2 - 1))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*y*z*(13*z**2 - 3) + y*z*(x**2 - y**2)*(13*z**2 - 3))
sphere_harm_grad_x.append( lambda x, y , z :-6*x*y*(143*z**4 - 66*z**2 + 3))
sphere_harm_grad_x.append( lambda x, y , z :y*z*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :0)
sphere_harm_grad_x.append( lambda x, y , z :-429*z**6 + 495*z**4 - 135*z**2 + 5)
sphere_harm_grad_x.append( lambda x, y , z :2*x*z*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_x.append( lambda x, y , z :2*x**2*(143*z**4 - 66*z**2 + 3) + (x**2 - 3*y**2)*(143*z**4 - 66*z**2 + 3))
sphere_harm_grad_x.append( lambda x, y , z :z*(4*x**3 - 12*x*y**2)*(13*z**2 - 3))
sphere_harm_grad_x.append( lambda x, y , z :x*(4*x**3 - 20*x*y**2)*(13*z**2 - 1) + (13*z**2 - 1)*(x**4 - 10*x**2*y**2 + 5*y**4))
sphere_harm_grad_x.append( lambda x, y , z :z*(6*x**5 - 60*x**3*y**2 + 30*x*y**4))
sphere_harm_grad_x.append( lambda x, y , z :x**6 - 21*x**4*y**2 + 35*x**2*y**4 + x*(6*x**5 - 84*x**3*y**2 + 70*x*y**4) - 7*y**6)

sphere_harm_grad_y = []
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :1)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :x)
sphere_harm_grad_y.append( lambda x, y , z :z)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y)
sphere_harm_grad_y.append( lambda x, y , z :-3*x**2 + 3*y**2)
sphere_harm_grad_y.append( lambda x, y , z :x*z)
sphere_harm_grad_y.append( lambda x, y , z :-5*z**2 + 1)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y*z)
sphere_harm_grad_y.append( lambda x, y , z :-6*x*y)
sphere_harm_grad_y.append( lambda x, y , z :-2*x*y**2 + x*(x**2 - y**2))
sphere_harm_grad_y.append( lambda x, y , z :2*y**2*z + z*(-3*x**2 + y**2))
sphere_harm_grad_y.append( lambda x, y , z :x*(7*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :z*(-7*z**2 + 3))
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y*(7*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :-6*x*y*z)
sphere_harm_grad_y.append( lambda x, y , z :-12*x**2*y + 4*y**3)
sphere_harm_grad_y.append( lambda x, y , z :5*x**4 - 10*x**2*y**2 + y**4 + y*(-20*x**2*y + 4*y**3))
sphere_harm_grad_y.append( lambda x, y , z :-2*x*y**2*z + x*z*(x**2 - y**2))
sphere_harm_grad_y.append( lambda x, y , z :2*y**2*(9*z**2 - 1) + (-3*x**2 + y**2)*(9*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :x*z*(3*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :21*z**4 - 14*z**2 + 1)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y*z*(3*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :-6*x*y*(9*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :z*(-12*x**2*y + 4*y**3))
sphere_harm_grad_y.append( lambda x, y , z :x*(-20*x**2*y + 20*y**3))
sphere_harm_grad_y.append( lambda x, y , z :x*y*(-20*x**2*y + 12*y**3) + x*(3*x**4 - 10*x**2*y**2 + 3*y**4))
sphere_harm_grad_y.append( lambda x, y , z :y*z*(-20*x**2*y + 4*y**3) + z*(5*x**4 - 10*x**2*y**2 + y**4))
sphere_harm_grad_y.append( lambda x, y , z :-2*x*y**2*(11*z**2 - 1) + x*(x**2 - y**2)*(11*z**2 - 1))
sphere_harm_grad_y.append( lambda x, y , z :2*y**2*z*(11*z**2 - 3) + z*(-3*x**2 + y**2)*(11*z**2 - 3))
sphere_harm_grad_y.append( lambda x, y , z :x*(33*z**4 - 18*z**2 + 1))
sphere_harm_grad_y.append( lambda x, y , z :z*(33*z**4 - 30*z**2 + 5))
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y*(33*z**4 - 18*z**2 + 1))
sphere_harm_grad_y.append( lambda x, y , z :-6*x*y*z*(11*z**2 - 3))
sphere_harm_grad_y.append( lambda x, y , z :(11*z**2 - 1)*(-12*x**2*y + 4*y**3))
sphere_harm_grad_y.append( lambda x, y , z :x*z*(-20*x**2*y + 20*y**3))
sphere_harm_grad_y.append( lambda x, y , z :-30*x**4*y + 60*x**2*y**3 - 6*y**5)
sphere_harm_grad_y.append( lambda x, y , z :-7*x**6 + 35*x**4*y**2 - 21*x**2*y**4 + y**6 + y*(70*x**4*y - 84*x**2*y**3 + 6*y**5))
sphere_harm_grad_y.append( lambda x, y , z :x*y*z*(-20*x**2*y + 12*y**3) + x*z*(3*x**4 - 10*x**2*y**2 + 3*y**4))
sphere_harm_grad_y.append( lambda x, y , z :y*(13*z**2 - 1)*(-20*x**2*y + 4*y**3) + (13*z**2 - 1)*(5*x**4 - 10*x**2*y**2 + y**4))
sphere_harm_grad_y.append( lambda x, y , z :-2*x*y**2*z*(13*z**2 - 3) + x*z*(x**2 - y**2)*(13*z**2 - 3))
sphere_harm_grad_y.append( lambda x, y , z :2*y**2*(143*z**4 - 66*z**2 + 3) + (-3*x**2 + y**2)*(143*z**4 - 66*z**2 + 3))
sphere_harm_grad_y.append( lambda x, y , z :x*z*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_y.append( lambda x, y , z :-429*z**6 + 495*z**4 - 135*z**2 + 5)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :0)
sphere_harm_grad_y.append( lambda x, y , z :-2*y*z*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_y.append( lambda x, y , z :-6*x*y*(143*z**4 - 66*z**2 + 3))
sphere_harm_grad_y.append( lambda x, y , z :z*(13*z**2 - 3)*(-12*x**2*y + 4*y**3))
sphere_harm_grad_y.append( lambda x, y , z :x*(13*z**2 - 1)*(-20*x**2*y + 20*y**3))
sphere_harm_grad_y.append( lambda x, y , z :z*(-30*x**4*y + 60*x**2*y**3 - 6*y**5))
sphere_harm_grad_y.append( lambda x, y , z :x*(-42*x**4*y + 140*x**2*y**3 - 42*y**5))

sphere_harm_grad_z = []
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :1)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :y)
sphere_harm_grad_z.append( lambda x, y , z :6*z)
sphere_harm_grad_z.append( lambda x, y , z :x)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :x*y)
sphere_harm_grad_z.append( lambda x, y , z :-10*y*z)
sphere_harm_grad_z.append( lambda x, y , z :15*z**2 - 3)
sphere_harm_grad_z.append( lambda x, y , z :-10*x*z)
sphere_harm_grad_z.append( lambda x, y , z :x**2 - y**2)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :y*(-3*x**2 + y**2))
sphere_harm_grad_z.append( lambda x, y , z :14*x*y*z)
sphere_harm_grad_z.append( lambda x, y , z :-14*y*z**2 + y*(-7*z**2 + 3))
sphere_harm_grad_z.append( lambda x, y , z :140*z**3 - 60*z)
sphere_harm_grad_z.append( lambda x, y , z :-14*x*z**2 + x*(-7*z**2 + 3))
sphere_harm_grad_z.append( lambda x, y , z :14*z*(x**2 - y**2))
sphere_harm_grad_z.append( lambda x, y , z :x*(x**2 - 3*y**2))
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :x*y*(x**2 - y**2))
sphere_harm_grad_z.append( lambda x, y , z :18*y*z*(-3*x**2 + y**2))
sphere_harm_grad_z.append( lambda x, y , z :6*x*y*z**2 + x*y*(3*z**2 - 1))
sphere_harm_grad_z.append( lambda x, y , z :y*(84*z**3 - 28*z))
sphere_harm_grad_z.append( lambda x, y , z :63*z**4 - 70*z**2 + z*(252*z**3 - 140*z) + 15)
sphere_harm_grad_z.append( lambda x, y , z :x*(84*z**3 - 28*z))
sphere_harm_grad_z.append( lambda x, y , z :6*z**2*(x**2 - y**2) + (x**2 - y**2)*(3*z**2 - 1))
sphere_harm_grad_z.append( lambda x, y , z :18*x*z*(x**2 - 3*y**2))
sphere_harm_grad_z.append( lambda x, y , z :x**4 - 6*x**2*y**2 + y**4)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :y*(5*x**4 - 10*x**2*y**2 + y**4))
sphere_harm_grad_z.append( lambda x, y , z :22*x*y*z*(x**2 - y**2))
sphere_harm_grad_z.append( lambda x, y , z :22*y*z**2*(-3*x**2 + y**2) + y*(-3*x**2 + y**2)*(11*z**2 - 3))
sphere_harm_grad_z.append( lambda x, y , z :x*y*(132*z**3 - 36*z))
sphere_harm_grad_z.append( lambda x, y , z :y*z*(132*z**3 - 60*z) + y*(33*z**4 - 30*z**2 + 5))
sphere_harm_grad_z.append( lambda x, y , z :1386*z**5 - 1260*z**3 + 210*z)
sphere_harm_grad_z.append( lambda x, y , z :x*z*(132*z**3 - 60*z) + x*(33*z**4 - 30*z**2 + 5))
sphere_harm_grad_z.append( lambda x, y , z :(x**2 - y**2)*(132*z**3 - 36*z))
sphere_harm_grad_z.append( lambda x, y , z :22*x*z**2*(x**2 - 3*y**2) + x*(x**2 - 3*y**2)*(11*z**2 - 3))
sphere_harm_grad_z.append( lambda x, y , z :22*z*(x**4 - 6*x**2*y**2 + y**4))
sphere_harm_grad_z.append( lambda x, y , z :x*(x**4 - 10*x**2*y**2 + 5*y**4))
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :0)
sphere_harm_grad_z.append( lambda x, y , z :x*y*(3*x**4 - 10*x**2*y**2 + 3*y**4))
sphere_harm_grad_z.append( lambda x, y , z :26*y*z*(5*x**4 - 10*x**2*y**2 + y**4))
sphere_harm_grad_z.append( lambda x, y , z :26*x*y*z**2*(x**2 - y**2) + x*y*(x**2 - y**2)*(13*z**2 - 3))
sphere_harm_grad_z.append( lambda x, y , z :y*(-3*x**2 + y**2)*(572*z**3 - 132*z))
sphere_harm_grad_z.append( lambda x, y , z :x*y*z*(572*z**3 - 220*z) + x*y*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_z.append( lambda x, y , z :y*(-2574*z**5 + 1980*z**3 - 270*z))
sphere_harm_grad_z.append( lambda x, y , z :429*z**6 - 693*z**4 + 315*z**2 + z*(2574*z**5 - 2772*z**3 + 630*z) - 35)
sphere_harm_grad_z.append( lambda x, y , z :x*(-2574*z**5 + 1980*z**3 - 270*z))
sphere_harm_grad_z.append( lambda x, y , z :z*(x**2 - y**2)*(572*z**3 - 220*z) + (x**2 - y**2)*(143*z**4 - 110*z**2 + 15))
sphere_harm_grad_z.append( lambda x, y , z :x*(x**2 - 3*y**2)*(572*z**3 - 132*z))
sphere_harm_grad_z.append( lambda x, y , z :26*z**2*(x**4 - 6*x**2*y**2 + y**4) + (13*z**2 - 3)*(x**4 - 6*x**2*y**2 + y**4))
sphere_harm_grad_z.append( lambda x, y , z :26*x*z*(x**4 - 10*x**2*y**2 + 5*y**4))
sphere_harm_grad_z.append( lambda x, y , z :x**6 - 15*x**4*y**2 + 15*x**2*y**4 - y**6)
sphere_harm_grad_z.append( lambda x, y , z :0)

def gen_sphere_harm_basis(nodes, degree, projectors):
    x, y , z = nodes[:,0], nodes[:,1], nodes[:,2]
    num_cols = (degree + 1)**2
    P = np.zeros((n, num_cols))
    j = 0
    for i in range(num_cols):
        P[:,i] = sphere_harm[i](x,y,z)
        
    rhs_x = np.zeros(P.shape)
    rhs_y = np.zeros(P.shape)
    rhs_z = np.zeros(P.shape)
    for col in range(num_cols):
        for row, (node, proj) in enumerate(zip(nodes, projectors)):
            gradient = np.array([sphere_harm_grad_x[col](*node), 
                        sphere_harm_grad_y[col](*node), 
                        sphere_harm_grad_z[col](*node)])
            rhs_x[row, col] = proj[0] @ gradient
            rhs_y[row, col] = proj[1] @ gradient
            rhs_z[row, col] = proj[2] @ gradient
    rhs_x, rhs_y, rhs_z = rhs_x.T, rhs_y.T, rhs_z.T
    return P, rhs_x, rhs_y, rhs_z

In [7]:
n = 5

indices = np.arange(0, n, dtype=float) + 0.5
phi = np.arccos(1 - 2*indices/n)
theta = np.pi * (1 + 5**0.5) * indices
xs, ys, zs = np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)
nodes = np.array([(x,y,z) for x,y,z in zip(xs,ys,zs)])
projectors = [np.eye(3) - np.outer(node, node) for node in nodes]

In [11]:
P, rhs_x, rhs_y, rhs_z = gen_sphere_harm_basis(nodes, 3, projectors)

In [12]:
rhs_x

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.21588253e-01,  3.33312316e-01, -2.68364026e-01,
        -3.72728340e-01,  6.86801535e-02],
       [-1.73939947e-01,  3.28766013e-01, -5.87919004e-17,
        -1.90334043e-01, -9.33562635e-02],
       [ 9.52726398e-01,  3.24455678e-01,  7.81223526e-02,
         7.73580950e-01,  9.86382200e-01],
       [-5.06346819e-01, -1.42377453e-01, -2.35832779e-01,
        -4.28599622e-01,  5.72513131e-01],
       [ 1.94541205e-01,  2.66649852e-01, -3.28651146e-17,
         2.98182672e-01, -1.09888246e-01],
       [-8.34911747e-01,  7.89038432e-01, -2.15997938e-32,
         4.56801703e-01,  4.48110065e-01],
       [ 7.24362237e-01, -1.40435457e-01, -5.16651111e-17,
        -2.18864760e-01, -7.78211520e-01],
       [ 5.50281981e-01, -8.03687188e-01,  3.00035019e-01,
        -1.32012066e+00, -3.11054761e-01],
       [ 7.91869855e-01,  1.37814023e-01,  5.53509330e-01,
        -2.16293190e+00

In [10]:
rhs_y

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 6.87273602e-01,  8.35544322e-01,  9.21877647e-01,
         3.86419050e-01,  6.53617800e-01],
       [ 4.47375563e-01, -1.62212541e-01, -1.71146693e-17,
        -3.13325633e-01,  4.70833950e-01],
       [ 1.21588253e-01,  3.33312316e-01, -2.68364026e-01,
        -3.72728340e-01,  6.86801535e-02],
       [ 8.14359011e-02, -5.51577844e-01,  8.10127088e-01,
         1.08091607e-01, -3.58529595e-02],
       [ 2.99637763e-01,  2.68435457e-01,  5.16651111e-17,
         9.08647603e-02, -2.45788480e-01],
       [ 2.14740270e+00, -3.89310099e-01, -6.28782751e-33,
         7.51981518e-01, -2.26000296e+00],
       [ 1.94541205e-01,  2.66649852e-01, -3.28651146e-17,
         2.98182672e-01, -1.09888246e-01],
       [ 8.21546173e-01, -1.22558764e+00, -1.03067308e+00,
         9.60089426e-01, -7.85392932e-01],
       [ 6.36018318e-01, -6.14529043e-01, -1.90140193e+00,
         1.28237870e+00

In [74]:
p = projectors[0]
p[0] @ p[0]

0.9527263980540975

In [41]:
projectors[0]

array([[ 0.9527264 ,  0.12158825, -0.17393995],
       [ 0.12158825,  0.6872736 ,  0.44737556],
       [-0.17393995,  0.44737556,  0.36      ]])

In [51]:
p@p

array([[ 0.9527264 ,  0.12158825, -0.17393995],
       [ 0.12158825,  0.6872736 ,  0.44737556],
       [-0.17393995,  0.44737556,  0.36      ]])