In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [26]:
def gen_sphere_harm_basis(nodes, degree):
    x, y , z = nodes[:,0], nodes[:,1], nodes[:,2]
    num_cols = (degree + 1)**2
    P = np.zeros((n, num_cols))
    j = 0
    for k in range(degree+1):
        if k == 0:
            P[:,j] = 1+0*x
            j += 1
        if k == 1:
            P[:,j] = y
            j += 1
            P[:,j] = z
            j += 1
            P[:,j] = x
            j += 1
        if k == 2:
            P[:,j] = x*y
            j += 1
            P[:,j] = y*z
            j += 1
            P[:,j] = 3*z**2 - 1
            j += 1
            P[:,j] = x*z
            j += 1
            P[:,j] = x**2 - y**2
            j += 1
        if k == 3:
            P[:,j] = y*(-3*x**2 + y**2)
            j += 1
            P[:,j] = x*y*z
            j += 1
            P[:,j] = y*(1 - 5*z**2)
            j += 1
            P[:,j] = z*(-3 + 5*z**2)
            j += 1
            P[:,j] = x*(1 - 5*z**2)
            j += 1
            P[:,j] = z*(x**2 - y**2)
            j += 1
            P[:,j] = x*(x**2 - 3*y**2)
            j += 1
        if k == 4:
            P[:,j] = x*y*(x**2 - y**2)
            j += 1
            P[:,j] = y*z*(y**2 - 3*x**2)
            j += 1
            P[:,j] = x*y*(-1 + 7*z**2)
            j += 1
            P[:,j] = y*z*(3 - 7*z**2)
            j += 1
            P[:,j] = 35*z**4 - 30*z**2 + 3
            j += 1
            P[:,j] = x*z*(3 - 7*z**2)
            j += 1
            P[:,j] = (x**2 - y**2)*(-1 + 7*z**2)
            j += 1
            P[:,j] = x*z*(x**2 - 3*y**2)
            j += 1
            P[:,j] = x**4 - 6*x**2*y**2 + y**4
            j += 1
        if k == 5:
            P[:,j] = y*(5*x**4-10*x**2*y**2+ y**4)
            j += 1
            P[:,j] = x*y*(x**2-1*y**2)*z
            j += 1
            P[:,j] = y*(-3*x**2+y**2)*(-1+9*z**2)
            j += 1
            P[:,j] = x*y*z*(-1+3*z**2)
            j += 1
            P[:,j] = y*(1-14*z**2+21*z**4)
            j += 1
            P[:,j] = z*(15-70*z**2+63*z**4)
            j += 1
            P[:,j] = x*(1-14*z**2+21*z**4)
            j += 1
            P[:,j] = (x**2-y**2)*z*(-1+3*z**2)
            j += 1
            P[:,j] = x*(x**2-3*y**2)*(-1+9*z**2)
            j += 1
            P[:,j] = (x**4-6*x**2*y**2+y**4)*z
            j += 1
            P[:,j] = x*(x**4-10*x**2*y**2+5*y**4)
            j += 1
        if k == 6:
            P[:,j] = x*y*(3*x**4-10*x**2*y**2+3*y**4)            
            j += 1
            P[:,j] = y*(5*x**4-10*x**2*y**2+y**4)*z
            j += 1
            P[:,j] = x*y*(x**2-y**2)*(-1+11*z**2)
            j += 1
            P[:,j] = y*(-3*x**2+y**2)*z*(-3+11*z**2)
            j += 1
            P[:,j] = x*y*(1-18*z**2+33*z**4)
            j += 1
            P[:,j] = y*z*(5-30*z**2+33*z**4)
            j += 1
            P[:,j] = (-5+105*z**2-315*z**4+231*z**6)
            j += 1
            P[:,j] = x*z*(5-30*z**2+33*z**4)
            j += 1
            P[:,j] = (x**2-y**2)*(1-18*z**2+33*z**4)
            j += 1
            P[:,j] = x*(x**2-3*y**2)*z*(-3+11*z**2)
            j += 1
            P[:,j] = (x**4-6*x**2*y**2+y**4)*(-1+11*z**2)
            j += 1
            P[:,j] = x*(x**4-10*x**2*y**2+5*y**4)*z
            j += 1
            P[:,j] = (x**6-15*x**4*y**2+15*x**2*y**4-y**6)
            j += 1
        if k == 7:
            P[:,j] = y*((-7)*x**6+35*x**4*y**2+(-21)*x**2*y**4+y**6)
            j += 1
            P[:,j] = x*y*(3*x**4+(-10)*x**2*y**2+3*y**4)*z
            j += 1
            P[:,j] = y*(5*x**4+(-10)*x**2*y**2+y**4)*((-1)+13*z**2)
            j += 1
            P[:,j] = x*y*(x**2+(-1)*y**2)*z*((-3)+13*z**2)
            j += 1
            P[:,j] = y*((-3)*x**2+y**2)*(3+(-66)*z**2+143*z**4)
            j += 1
            P[:,j] = x*y*z*(15+(-110)*z**2+143*z**4)
            j += 1
            P[:,j] = y*(5+(-135)*z**2+495*z**4+(-429)*z**6)
            j += 1
            P[:,j] = z*((-35)+315*z**2+(-693)*z**4+429*z**6)
            j += 1
            P[:,j] = x*(5+(-135)*z**2+495*z**4+(-429)*z**6)
            j += 1
            P[:,j] = (x**2+(-1)*y**2)*z*(15+(-110)*z**2+143*z**4)
            j += 1
            P[:,j] = x*(x**2+(-3)*y**2)*(3+(-66)*z**2+143*z**4)
            j += 1
            P[:,j] = (x**4+(-6)*x**2*y**2+y**4)*z*((-3)+13*z**2)
            j += 1
            P[:,j] = x*(x**4+(-10)*x**2*y**2+5*y**4)*((-1)+13*z**2)
            j += 1
            P[:,j] = (x**6+(-15)*x**4*y**2+15*x**2*y**4+(-1)*y**6)*z
            j += 1
            P[:,j] = x*(x**6+(-21)*x**4*y**2+35*x**2*y**4+(-7)*y**6)
            j += 1
            
    rhs_x = np.zeros((n, num_cols))
    
    rhs_y = np.zeros((n, num_cols))
    
    rhs_z = np.zeros((n, num_cols))
    
    return P

In [27]:
n = 5

indices = np.arange(0, n, dtype=float) + 0.5
phi = np.arccos(1 - 2*indices/n)
theta = np.pi * (1 + 5**0.5) * indices
xs, ys, zs = np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)
nodes = np.array([(x,y,z) for x,y,z in zip(xs,ys,zs)])

In [28]:
nodes

array([[ 2.17424934e-01, -5.59219454e-01,  8.00000000e-01],
       [-8.21915033e-01,  4.05531353e-01,  4.00000000e-01],
       [ 9.60144597e-01,  2.79503761e-01,  6.12323400e-17],
       [-4.75835108e-01, -7.83314082e-01, -4.00000000e-01],
       [-1.16695329e-01,  5.88542437e-01, -8.00000000e-01]])

In [43]:
P = gen_sphere_harm_basis(nodes, 7)

In [44]:
print(P[:,4] - nodes[:,0]*nodes[:,1])

[0. 0. 0. 0. 0.]


In [46]:
P.shape

(5, 64)

In [36]:
xs

array([ 0.21742493, -0.82191503,  0.9601446 , -0.47583511, -0.11669533])

In [37]:
nodes

array([[ 2.17424934e-01, -5.59219454e-01,  8.00000000e-01],
       [-8.21915033e-01,  4.05531353e-01,  4.00000000e-01],
       [ 9.60144597e-01,  2.79503761e-01,  6.12323400e-17],
       [-4.75835108e-01, -7.83314082e-01, -4.00000000e-01],
       [-1.16695329e-01,  5.88542437e-01, -8.00000000e-01]])